### ISSUE TITLE
NumberLong conversion

### ISSUE THREAD

**Issue by ddperdue** [watson/json2mongo#4]
I'm using node-mongo-seeds which uses json2mongo. I'm seeing some strange behavior when trying to seed longs.

Inserting something like:
`"twoMinAggregatedStartTime" : {"$numberLong" : "1491091200000"}`

Results in:

`"twoMinAggregatedStartTime" : NumberLong(737548288)`

It looks like it's only storing the 32 bit integer value of the 64 bit Long value (32 least significant bits of 1491091200000 is 737548288).

I looked at the mongodb node driver docs and I think maybe the way you're creating a Long is incorrect. 

http://mongodb.github.io/node-mongodb-native/2.2/api/Long.html

It looks like what you have is:

`mongo.Long(val)`
but the api is expecting the high bits and the low bits as two separate arguments

I believe it should be:

`mongo.Long.fromString(val)`

http://mongodb.github.io/node-mongodb-native/2.2/api/Long.html#.fromString

I'd be up for submitting a pull request if it's not something that you have time to look into.

**Comment by watson** [comment]
Fixed by #5
